### PR TITLE
Add Sonos audio source

### PR DESCRIPTION
**Pull request by stnkl**
I've been using audio-band for a while now but it was always missing a way to control my local Sonos device when I'm not controlling it indirectly via the Spotify app on my computer.

I added a new audio source for controlling Sonos devices. Tested with a single Sonos Play:3 on my local network while playing from Spotify (mobile app) or streaming directly from the mobile Sonos app.

I've been using parts of [madnessxd/Sonos-API-C-Sharp](https://github.com/madnessxd/Sonos-API-C-Sharp).

### CODE REVIEW

**Comment by dsafa** [comment]
It looks good.
The only issue that I have is that I can't maintain it since I don't have a Sonos device. I'm sure that you would help maintain it but I hope that you see my concern.

Here's my proposal:
The earliest goal that I had for this project was that other people could develop their own audio sources. What I suggest is that you keep it in your own repository and I will link your repo in the readme. There are a few issues with this: I haven't nailed down the api and there is no documentation. I also haven't created the nuget package for it yet so development is harder. I will be focusing on getting it done so that you shouldn't have to wait too long.

I would love comments or suggestions

**Comment by stnkl** [comment]
That's totally understandable. Maybe in the future audio-band could have a system to install audio sources as addons. But I think that's what you have in mind too.

**Comment by dsafa** [comment]
Thanks for understanding. I did not really consider a system for installing and was planning to just leave it as it is with subfolders. But it sounds like a good idea.
I'll try to get the plugin stuff nailed down soon.

**Comment by dsafa** [comment]
Hey, I finally manage to get the initial version down in the [latest release](https://github.com/dsafa/audio-band/releases/tag/v0.7.9). I can't promise that the api won't change but I think it is in a good state for now. Give it a try, I'll be working on the documentation pages next.

**Comment by stnkl** [comment]
Great! I'll give it another go when I get the time.

**Comment by stnkl** [comment]
Hey, I got around to implementing it as a plugin using your new interface: https://github.com/stnkl/audio-band-sonos It works great! Maybe I'll make another one for foobar2000 soon.

I will close this pull request now.

**Pull request closed without merging**
